import fs from 'node:fs';
import assert from 'node:assert/strict';
const registry=fs.readFileSync('js/advanced-tools/registry.js','utf8');
const host=fs.readFileSync('js/advanced-tools/host.js','utf8');
const render=fs.readFileSync('js/advanced-tools/render-adapter.js','utf8');
const project=fs.readFileSync('js/advanced-tools/project-adapter.js','utf8');
const hardening=fs.readFileSync('js/advanced-tools/hardening.js','utf8');
const html=fs.readFileSync('advanced-tool.html','utf8');
const rubik=fs.readFileSync('js/rubik-tools-ui.js','utf8');
const docs=fs.readFileSync('docs/architecture/advanced-module-type-b-v1.md','utf8');

assert.match(registry,/infinite-display-studio-pro/);
assert.match(registry,/89ee1beb56a0c86c06366bbbb155f421e2d23981/);
assert.match(registry,/f74424403b3dd276919035e86b3b0abb1c48224c/);
for(const mode of ['spiral','curl','bands','drift','parallax','galaxy','dna','vortex','kaleidoscope','fallingrain','mobius','explodedgrid']) assert.match(registry,new RegExp("v:'"+mode+"'"),`Missing mode ${mode}`);
assert.match(host,/buildRuntimeSource/);
assert.match(host,/ESCAPARATES PRO TYPE B RUNTIME BRIDGE/);
assert.match(host,/InfiniteDisplayTypeB/);
assert.match(host,/sourceCommit:'89ee1beb56a0c86c06366bbbb155f421e2d23981'/);
assert.match(host,/setConfig:__epApplyConfig/);
assert.match(host,/setBranding:__epApplyBranding/);
assert.match(host,/setMedia:__epSetMedia/);
assert.match(host,/getCanvas:/);
assert.match(hardening,/EP\.ControlSchema\.validateValue/);
assert.match(hardening,/gitBlobSha/);
assert.match(hardening,/source integrity failed/);
assert.match(render,/captureStream/);
assert.match(project,/config:\{advancedTool:/);
assert.match(project,/templateId:'advanced-tool\//);
assert.match(html,/js\/customization\/project-store-local\.js/);
assert.match(html,/js\/projects\/project-versioning\.js/);
assert.match(html,/js\/advanced-tools\/hardening\.js/);
assert.match(html,/js\/advanced-tools\/host\.js/);
assert.match(rubik,/Infinite Display Studio PRO/);
assert.match(rubik,/integrationType: 'type-b'/);
assert.match(rubik,/advanced-tool\.html\?tool=infinite-display-studio-pro/);
assert.match(docs,/PRESERVE ENGINE/);
assert.doesNotMatch(rubik,/labs\/rubik-sota-tools\/infinite-display-studio-pro/, 'Type B must not masquerade as a Type A standalone copy');
console.log('Advanced Tool Type B contract OK');
