(function(){
  'use strict';
  window.EP=window.EP||{};
  function safeName(name,index){var ext=(String(name||'').match(/\.[a-z0-9]{2,6}$/i)||[''])[0].toLowerCase();var base=String(name||('asset-'+(index+1))).replace(ext,'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||('asset-'+(index+1));return base+ext;}
  async function fetchBlob(url){var res=await fetch(url,{credentials:'omit'});if(!res.ok)throw new Error('No se pudo descargar el asset: '+url);return res.blob();}
  async function build(project,html){if(!window.JSZip)throw new Error('JSZip no está disponible.');var validated=EP.HtmlExport.build(project,html),zip=new JSZip(),root=zip.folder(EP.HtmlExport.slug(project.name)),assetsFolder=root.folder('assets'),manifest={name:project.name,templateId:project.templateId,templateVersion:project.templateVersion||'2.2.0',exportedAt:new Date().toISOString(),assets:[]},rewritten=validated.html,seen={};for(var i=0;i<(project.media||[]).length;i++){var m=project.media[i];if(!m)continue;var url=m.publicUrl||m.url;if(!url||seen[url])continue;var filename=safeName(m.name||('asset-'+(i+1)),i);while(manifest.assets.some(function(a){return a.path==='assets/'+filename}))filename='asset-'+(i+1)+'-'+filename;var blob=await fetchBlob(url);assetsFolder.file(filename,blob);rewritten=rewritten.split(url).join('./assets/'+filename);manifest.assets.push({slot:i+1,name:m.name||filename,path:'assets/'+filename,mimeType:m.mimeType||m.type||blob.type,size:blob.size});seen[url]=filename;}root.file('index.html',rewritten);root.file('manifest.json',JSON.stringify(manifest,null,2));root.file('README.md','# '+project.name+'\n\nExportado desde Escaparates Pro.\n\n## Publicación\nSube esta carpeta completa a un hosting estático. No elimines la carpeta `assets`.\n\n## Contenido\n- `index.html`: landing principal\n- `assets/`: imágenes, vídeos y fuentes\n- `manifest.json`: inventario técnico del proyecto\n');var output=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});return {filename:EP.HtmlExport.slug(project.name)+'.zip',blob:output,manifest:manifest,report:validated.report};}
  function download(result){var a=document.createElement('a');a.href=URL.createObjectURL(result.blob);a.download=result.filename;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1500);}
  EP.ZipExport={build:build,download:download,safeName:safeName};
})();
