window.RealEstateStoryStore=(function(){
  var DB='real-estate-storytelling-studio-pro',VERSION=1,PROJECT='project',MEDIA='media';
  function clone(o){return JSON.parse(JSON.stringify(o));}
  function open(){return new Promise(function(res,rej){var r=indexedDB.open(DB,VERSION);r.onupgradeneeded=function(){var db=r.result;if(!db.objectStoreNames.contains(PROJECT))db.createObjectStore(PROJECT);if(!db.objectStoreNames.contains(MEDIA))db.createObjectStore(MEDIA);};r.onsuccess=function(){res(r.result)};r.onerror=function(){rej(r.error)};});}
  async function put(store,key,val){var db=await open();return new Promise(function(res,rej){var tx=db.transaction(store,'readwrite');tx.objectStore(store).put(val,key);tx.oncomplete=function(){db.close();res();};tx.onerror=function(){db.close();rej(tx.error);};});}
  async function get(store,key){var db=await open();return new Promise(function(res,rej){var tx=db.transaction(store,'readonly'),rq=tx.objectStore(store).get(key);rq.onsuccess=function(){var v=rq.result;db.close();res(v);};rq.onerror=function(){db.close();rej(rq.error);};});}
  async function getAllMedia(){var db=await open();return new Promise(function(res,rej){var tx=db.transaction(MEDIA,'readonly'),os=tx.objectStore(MEDIA),rq=os.getAllKeys();rq.onsuccess=function(){var keys=rq.result||[],out={},left=keys.length;if(!left){db.close();res(out);return;}keys.forEach(function(k){var r=os.get(k);r.onsuccess=function(){out[k]=r.result;if(--left===0){db.close();res(out);}};r.onerror=function(){db.close();rej(r.error);};});};rq.onerror=function(){db.close();rej(rq.error);};});}
  async function reset(){var db=await open();return new Promise(function(res,rej){var tx=db.transaction([PROJECT,MEDIA],'readwrite');tx.objectStore(PROJECT).clear();tx.objectStore(MEDIA).clear();tx.oncomplete=function(){db.close();res();};tx.onerror=function(){db.close();rej(tx.error);};});}
  return{clone:clone,loadProject:async function(def){return clone(await get(PROJECT,'current')||def);},saveProject:function(p){return put(PROJECT,'current',clone(p));},saveMedia:function(slot,file){return put(MEDIA,slot,{file:file,name:file.name,type:file.type,updated:Date.now()});},loadMedia:getAllMedia,reset:reset};
})();
