(function(){
  'use strict';
  window.EP=window.EP||{};
  function Manager(options){options=options||{};this.onStatus=options.onStatus||function(){};this.onProject=options.onProject||function(){};this.project=null;this.sync=new EP.ProjectSync.Sync({onStatus:this.handleSync.bind(this)});}
  Manager.prototype.handleSync=function(status,payload,operation){this.onStatus(status,payload,operation);if(status==='synced'&&payload&&payload.project){this.project=payload.project;this.onProject(this.project);}};
  Manager.prototype.open=async function(id){var remote=await EP.ProjectClient.api.get(id);this.project=remote.project||remote;await EP.ProjectStoreLocal.save(this.project);this.onProject(this.project);return this.project;};
  Manager.prototype.create=async function(project){var local=await EP.ProjectStoreLocal.save(project);this.project=local;this.onProject(local);if(EP.ProjectClient.hasSession()&&navigator.onLine){try{var remote=await EP.ProjectClient.api.create(local);this.project=remote.project||remote;await EP.ProjectStoreLocal.save(this.project);this.onStatus('synced');this.onProject(this.project);return this.project;}catch(e){await this.sync.enqueue({type:'create',payload:local});}}else await this.sync.enqueue({type:'create',payload:local});return local;};
  Manager.prototype.save=async function(project,options){options=options||{};var local=await EP.ProjectStoreLocal.save(project);this.project=local;this.onStatus('saved-local');this.onProject(local);var operation=local.cloudId?{type:'update',projectId:local.cloudId,payload:local,revision:local.revision}:{type:'create',payload:local};await this.sync.enqueue(operation);if(options.flush!==false)await this.sync.flush();return local;};
  Manager.prototype.duplicate=async function(project,name){var copy=EP.ProjectStoreLocal.fork?EP.ProjectStoreLocal.fork(project,name):JSON.parse(JSON.stringify(project));return this.create(copy);};
  Manager.prototype.remove=async function(project){if(project.cloudId)await this.sync.enqueue({type:'delete',projectId:project.cloudId});if(project.id)await EP.ProjectStoreLocal.remove(project.id);this.project=null;this.onProject(null);};
  Manager.prototype.publish=async function(project,payload){if(!project.cloudId)throw new Error('El proyecto debe estar sincronizado antes de publicar.');var result=await EP.ProjectClient.api.publish(project.cloudId,payload||{});project.published=result.publication||result;if(result&&result.revision!=null)project.revision=result.revision;project.status='published';var local=await EP.ProjectStoreLocal.save(project);this.project=local;this.onProject(local);return local;};
  Manager.prototype.unpublish=async function(project){if(!project.cloudId)throw new Error('Proyecto no sincronizado.');var result=await EP.ProjectClient.api.unpublish(project.cloudId);project.published=null;project.status='draft';if(result&&result.revision!=null)project.revision=result.revision;var local=await EP.ProjectStoreLocal.save(project);this.project=local;this.onProject(local);return local;};
  Manager.prototype.destroy=function(){this.sync.destroy();};
  EP.ProjectManager={Manager:Manager};
})();
